-- ============================================================
-- UP MIGRATION
-- Create assembly table
-- ============================================================


CREATE TABLE assembly_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tenant_id INT NOT NULL,

    machine_id VARCHAR(100) NOT NULL,

    assembly_name VARCHAR(255) NOT NULL,

    device_id VARCHAR(100) NOT NULL,

    station VARCHAR(100),

    variant VARCHAR(100) NOT NULL DEFAULT 'none',

    hour_target_output INT NOT NULL DEFAULT 0,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    created_by INT,

    updated_by INT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

-- ========================================================
-- FOREIGN KEY
-- ========================================================

CONSTRAINT fk_assembly_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE,

-- ========================================================
-- UNIQUE CONSTRAINT
--
-- Same machine can have multiple variants:
--
-- tenant 1 + ASM-001 + none
-- tenant 1 + ASM-001 + V1
-- tenant 1 + ASM-001 + V2
--
-- But the same combination cannot be duplicated.
-- device_id is intentionally NOT included.
-- ========================================================

CONSTRAINT uq_assembly_tenant_machine_variant UNIQUE (
    tenant_id,
    machine_id,
    variant
),

-- ========================================================
-- VALIDATION
-- ========================================================

CONSTRAINT chk_assembly_hour_target_output
        CHECK (hour_target_output >= 0)
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_assembly_tenant_id ON assembly (tenant_id);

CREATE INDEX idx_assembly_machine_id ON assembly (machine_id);

CREATE INDEX idx_assembly_device_id ON assembly (device_id);

CREATE INDEX idx_assembly_station ON assembly (station);

CREATE INDEX idx_assembly_tenant_active ON assembly (tenant_id, is_active)
WHERE
    is_deleted = FALSE;